### ISSUE TITLE
Not capturing partial harvest biomass or deadwood

### ISSUE THREAD

**Issue by CarenD** [LANDIS-II-Foundation/Extension-Biomass-Succession#17]
When biomassHarvest is used for partial cohort mortality with BiomassSuccession, the biomass reduction is happening appropriately. However, there is no tracking of that biomass removed from the ecosystem for the user, and the appropriate increase of deadwood is not done.

The output to the screen “Partial Reduction…” is not printed by the Biomass Succession model. 

The Biomass Succession model does still not enter the PlugIn.CohortPartialMortality routine, which means that it (or my ForCS model) cannot capture the CWD input from the reduction in biomass. The cohort library deals with actually carrying the new biomass values so the succession model knows about it, but we want the succession models to know how much reduction has occurred from the harvesting.

debugging lines:
            PlugIn.ModelCore.UI.WriteLine("EVENT: Cohort Partial Mortality: species={0}, age={1}, disturbance={2}.", cohort.Species.Name, cohort.Age, disturbanceType);
            PlugIn.ModelCore.UI.WriteLine("       Cohort Reductions:  Foliar={0:0.00}.  Wood={1:0.00}.", cohortReductions.Foliar, cohortReductions.Wood);
            PlugIn.ModelCore.UI.WriteLine("       InputB/TotalB:  Foliar={0:0.00}/{1:0.00}, Wood={2:0.0}/{3:0.0}.", foliarInput, foliar, woodInput, wood);

**Comment by CarenD** [comment]
this shouldn't have been closed

**Comment by rmscheller** [comment]
Caren,
Given the date of the original issue, could you test to see if the behavior persists?  Many changes in the conversion to Core v7 may have resolved the underlying problem.

**Comment by CarenD** [comment]
Hi
I can’t test it because I haven’t moved to v7 of the core yet. We are working on getting a new version of ForCS running but it’s taken much longer than I anticipate.

Can you?

Caren

778-974-5655 (Victoria area code)

**Comment by rmscheller** [comment]
I created and documented a test of the behavior:

https://github.com/LANDIS-II-Foundation/Extension-Biomass-Succession/tree/master/testings/v5_SingleCell_BiomassHarvest

See the Readme for more information.  It passes the tests as I have created them.

Some updates were required:

https://github.com/LANDIS-II-Foundation/Extension-Biomass-Succession/commit/882f6d088333e769c78bf1584f5621e65bf383a1

**Comment by onetreetwotrees** [comment]
Rob,

I am looking through the changes to Biomass Succession that you just posted and I see that you changed fractionPartialMortality in PlugIn.cs from a fraction to something else. Did you check with how Biomass Insects or other partial mortality disturbance extensions pass mortality information before making this change? This looks like existing extensions will no longer work based on this change.

**Comment by rmscheller** [comment]
Jane,

I'm happy to test Biomass Insects if you have a v7 compatible release.

The only other extension that uses PartialMortality is Biomass Harvest, which was tested here.

**Comment by onetreetwotrees** [comment]
Biomass Harvest does not let you pass a partial harvest > 99%. I tried it using your example. It just sends an error message that the harvest has to be < 99%.

**Comment by onetreetwotrees** [comment]
I am looking through the Biomass Succession change log to trace the fractionPartialMortality change. It turns out you had changed this (current line 200 in Plugin.cs) in May/June 2018 and I sent you an e-mail on June 11th saying that it would cause downstream problems for Biomass Insects and possibly other disturbance extensions. The change that you made yesterday to line 200 Plugin.cs is changing it back to what it was.

**Comment by rmscheller** [comment]
Biomass harvest was updated to deal with the problem that if an event is flagged as a partial mortality event, it does not trigger cohort removal (and this causes other weird problems) and post-cohort removal regeneration.  And so the obvious solution (I'm sure there are others) was to not allow partial removals of 100%.  
Regarding other changes:  Surely not my last mistake!  I can change the name back.

**Comment by CarenD** [comment]
Doesn't the LUC extension rely on Biomass Harvesting code? It should be tested too.

**Comment by rmscheller** [comment]
The general order of operations is:
1. a disturbance extension indicates partial/total cohort mortality
2. a cohort library (there are multiple, depending on succession library) reduces cohort appropriately 
3. the succession extension uses that information to process dead cohort materials, change site conditions, launch regeneration (if total mortality).

So a change to a disturbance extension should not affect how dead wood is processed.   I don't know all the details of Eric's proposed Biomass Harvest changes but I don't see any reason why they would alter this process.  And he is aware of the effects on LUC.

**Comment by CarenD** [comment]
> Biomass Harvest does not let you pass a partial harvest > 99%. I tried it using your example. It just sends an error message that the harvest has to be < 99%.

Does that mean you can't use Biomass Harvest to do a 100% cohort removal anymore? That would be a problem for many users who want a combination of partial and full cohort removal on their landscape.

**Comment by rmscheller** [comment]
Caren,

No, you can just leave out the percentage (X%) and it will do complete removal.
