### ISSUE TITLE
Installer does not include Metadata library dll.

### ISSUE THREAD

**Issue by brmiranda** [LANDIS-II-Foundation/Extension-Biomass-Succession#18]
The latest Biomass Succession version includes a reference to the Metadata Library, but the installer script does not include the library.  Users who install the latest version and don't already have the Metadata library receive an error (see attached).
![biomasserror](https://user-images.githubusercontent.com/9326467/29522271-46d762ee-864e-11e7-881b-dac56b0c820a.png)

**Comment by bmarron18** [comment]
Metadata added to installer .iss; installer rebuilt. Issue can be closed.

**Comment by rmscheller** [comment]
Ditto.  Installer should be 4.0.1 to indicate minor bug fix.

**Comment by rmscheller** [comment]
Corrected and released.
