### ISSUE TITLE
Example files not working

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/Extension-Biomass-Succession#2]
Reported by AMGdeBruijn, Apr 15, 2014
What steps will reproduce the problem?
1. Download and install biomass succession package
2. Double click the batch file that comes with the example

What is the expected output? What do you see instead?
Model should run, instead error message "Error with the input value for the Mortality Curve Shape Parameter"

**Comment by bmarron18** [comment]
QAQC-tested example now included in installation; example files work; close issue
