### ISSUE TITLE
Excess information printing to console - "Partial Reduction: SpeciesName, Age yrs, XXXX Mg/ha"

### ISSUE THREAD

**Issue by onetreetwotrees** [LANDIS-II-Foundation/Extension-Biomass-Succession#22]
I downloaded and installed all the latest extension versions that Rob recently released and am now debugging the version of Biomass-Insects that is on Github (a non-working version was updated, so this needs to be fixed). When I am running the example scenario s2e2 under deploy\examples, a message is getting written to the console every time a cohort is partially reduced. This seems like a message that was used for debugging and will slow down and clutter large runs. An example of the message is:

Partial Reduction: PINURIGI, 43 yrs, 200 Mg/ha

PINURIGI is a species name from the example scenario. You may not be able to reproduce this error with the GitHub code, because it does not work as is and this arose as I'm debugging and getting it to work again. However, there is no print message with "Partial Reduction:" in the Biomass-Insects repo. I'm guessing it is somewhere in the Biomass Succession extension. Can someone familiar with this extension code confirm and possibly comment this message out from the release version? - Jane Foster

**Comment by rmscheller** [comment]
Jane,
Yes, probably a relic in Biomass Succession.  Austen, could you do a quick scan and fix?  Thanks!

**Comment by aruzicka555** [comment]
Code found and commented out. The code was actually in the Library-Biomass-Cohort repository, and I have submitted the pull request there.

**Comment by rmscheller** [comment]
Thanks!  Could you pull up to the support-dlls repo?

**Comment by aruzicka555** [comment]
Pull request submitted.

**Comment by bmarron18** [comment]
Repo rebuilt with most recent version of Landis.Library.BiomassCohorts-v2.dll
