### ISSUE TITLE
No overload for 'AddNewCohort' matches delegate 'Reproduction.Delegates.AddNewCohort'

### ISSUE THREAD

**Issue by glaroc** [LANDIS-II-Foundation/Extension-Biomass-Succession#30]
Hi, when I try to build this extension on Linux with "dotnet build", I get: 

PlugIn.cs(105,41): error CS0123: No overload for 'AddNewCohort' matches delegate 'Reproduction.Delegates.AddNewCohort'

I can succesfully build other extensions and I think I am modifying the .csproj file properly and I'm directing to the proper libraries files. 

@rmscheller ?

**Comment by rmscheller** [comment]
Guillaume,

The latest releases uses a new version of the succession library (v8) that changes that interface.  Are you using that version?

**Comment by glaroc** [comment]
The .csproj file mentions v8 but links to Landis.Library.Succession-v7.dll here       <HintPath>lib\Landis.Library.Succession-v7.dll</HintPath> 

I've changed it to Landis.Library.Succession-v8.dll and now it works! Thank you
