### ISSUE TITLE
Documentation not updated for v5.2

### ISSUE THREAD

**Issue by glaroc** [LANDIS-II-Foundation/Extension-Biomass-Succession#33]
Hi, the documentation (docs/LANDIS-II Biomass Succession v5.0 User Guide.pdf) still references the Age-only Disturbances file (see sections 1.1.8 and 6.2), but from my understanding, this has now been removed. Am I correct? 

Also, the main parameter example file described in 6.1 seems to be for an older version that doesn't have FireReductionParameters and HarvestReductionParameters.

**Comment by rmscheller** [comment]
Thanks, Guillaume!  Much appreciated.
