### ISSUE TITLE
Wrong climate library reference 

### ISSUE THREAD

**Issue by glaroc** [LANDIS-II-Foundation/Extension-Biomass-Succession#34]
Similar to a previous bug, the wrong climate library is referenced here: 

https://github.com/LANDIS-II-Foundation/Extension-Biomass-Succession/blob/88f4f6f5dfbe45827dcf322044d19adef138110e/src/biomass-succession.csproj#L43

I believe it should be lib\Landis.Library.Climate-v4.dll

**Comment by rmscheller** [comment]
Thanks, Guillaume.  VS auto inserts 'HintPaths' which are frustrating and unnecessary.  I have to diligently remove them even after I change the reference itself.
