### ISSUE TITLE
Suggestion of clarifications to the user guide

### ISSUE THREAD

**Issue by Klemet** [LANDIS-II-Foundation/Extension-Biomass-Succession#41]
Hello !

Just wanted to suggest some clarifications to the latest version of the user guide ([revision of September 30, 2021](https://github.com/LANDIS-II-Foundation/Extension-Biomass-Succession/blob/master/docs/LANDIS-II%20Biomass%20Succession%20v6%20User%20Guide.pdf)), in the section concerning the `HarvestReductionParameters` parameter table.

I think that it wasn't very clear for users that these parameters only influence transfers to the dead woody and leaf pools, and that they do not affect the live biomass pool in the sites (which is only influenced by the parameters of Biomass Harvest); especially when concerning the `Cohort Wood Removal` parameter which can be ambiguous in its name by suggesting that it influences the amount of live biomass harvested by the prescription (which it doesn't, to the best of my understanding).

I also though it was good to point out that in its current state, Biomass Succession will display a warning message in the terminal/logs for every prescription applied to a site that is not the list following the `HarvestReductionParameters` parameter; this can lead to very large and unreadable logs on large landscapes.

The clarifications that I propose are shown here :

![Revisions_BiomassSuccession_UserGuide_CH](https://github.com/LANDIS-II-Foundation/Extension-Biomass-Succession/assets/41070328/7cad876a-fd43-4982-90c6-07e2cb34d490)

I've put these clarification in the following .docx and .pdf files : 
[LANDIS-II Biomass Succession v6.0 User Guide.docx](https://github.com/LANDIS-II-Foundation/Extension-Biomass-Succession/files/13813987/LANDIS-II.Biomass.Succession.v6.0.User.Guide.docx)
[LANDIS-II Biomass Succession v6.0 User Guide.pdf](https://github.com/LANDIS-II-Foundation/Extension-Biomass-Succession/files/13813988/LANDIS-II.Biomass.Succession.v6.0.User.Guide.pdf)

If these modifications are deemed satisfactory, feel free to update the user guide files with a commit.

**Comment by rmscheller** [comment]
Thanks, Clement.
