### ISSUE TITLE
Wildcard behavior not working correctly for the Harvest Effects Table ?

### ISSUE THREAD

**Issue by Klemet** [LANDIS-II-Foundation/Extension-Biomass-Succession#42]
Hello !

I just started using wildcards in the Harvest Effects Table, as I use Magic Harvest to create new prescriptions on-the-fly during time steps to make for more complex planting regimes.

However, even if I indicate this in the table :

```
>> 		Prescription     	Dead Wood     Dead Litter     Cohort wood     Cohort Leaf
>>     		name         	Reduction      Reduction        Removal         Removal
>> 		-------------    	---------     ------------    ------------    ------------
			CPR*	 		0.1        		0.1        		0.5        0.8
```

I'm still getting the following error during Biomass Harvest run : 

```
WARNING: Prescription CPR-Planting:BETU.PAP-ACER.SAH not found in the Biomass Succession Harvest Effects Table
```

Same goes for all of the other prescriptions (they all use wildcards).

Looking at the code, it seems like the issue is in [ComparePrescriptionNames](https://github.com/LANDIS-II-Foundation/Extension-Biomass-Succession/blob/90436b029356de5b0d4f5d312744f03a9335eefc/src/HarvestEffects.cs#L208).

Reading it, it seems like the intended behavior of the function is to see if the prescription in Biomass Harvest (`harvestPrescriptionName`) matches one on the Harvest Effect Table (`tablePrescriptionName`); and if it doesn't, the function checks if the wildcard `*` is in `tablePrescriptionName`. If it exists, it tries to "trim" the name of `tablePrescriptionName` (remove the `*` at the end ), and check if `harvestPrescriptionName` contains the trimmed version.

The issue is that `tablePrescriptionName.TrimEnd()` at [line 218](https://github.com/LANDIS-II-Foundation/Extension-Biomass-Succession/blob/90436b029356de5b0d4f5d312744f03a9335eefc/src/HarvestEffects.cs#L218) does't remove `*` from `tablePrescriptionName`; since the function `TrimEnd()` is passed no arguments, [it only trims spaces](https://learn.microsoft.com/en-us/dotnet/api/system.string.trimend?view=net-8.0), and does not remove `*`.

I suggest that it should be changed for `tablePrescriptionName.TrimEnd('*')`, which should correctly trim the character `*` from `tablePrescriptionName`, and give the correct behavior as the check would then work.

I'll check it myself to see if it works !

**Comment by Klemet** [comment]
Can confirm, the problem is resolved by using `tablePrescriptionName.TrimEnd('*')` instead of `tablePrescriptionName.TrimEnd()`, even on an older version (5.3) that I just recompiled with this change.

**Comment by rmscheller** [comment]
Clement, 
Thank you again for your contribution!  Much appreciated.  I'll recode and commit now, although the change might not be released immediately.

**Comment by Klemet** [comment]
Most welcome, I'm glad if this can help 😄 !
