### ISSUE TITLE
Build failing on Linux in latest commit (9d13943847328e6fc8968120bc46802c8581541b) due to mismatch in interface ICalculator implementation in CohortBiomass.cs

### ISSUE THREAD

**Issue by Klemet** [LANDIS-II-Foundation/Extension-Biomass-Succession#48]
Everything is in the title !

Commit 9d13943847328e6fc8968120bc46802c8581541b (latest of of writing this) returns the following error when trying to build : 

```
/usr/bin/LANDIS_Linux/Extension-Biomass-Succession/src/CohortBiomass.cs(16,11): error CS0535: 'CohortBiomass' does not implement interface member 'ICalculator.ComputeChange(ICohort, ActiveSite, out double, out ExpandoObject)' [/usr/bin/LANDIS_Linux/Extension-Biomass-Succession/src/biomass-succession.csproj]
```

It seems that the problem comes from the `ComputeChange()` function at [line 60 of CohortBiomass.cs](https://github.com/LANDIS-II-Foundation/Extension-Biomass-Succession/blob/9d13943847328e6fc8968120bc46802c8581541b/src/CohortBiomass.cs#L60) : the function outs the variable `ANPP` as an `int`, but the interface expects a `double`.

Modifying the line on linux with `sed -i '62s/.*/                                 out double ANPP,/' CohortBiomass.cs` to replace the `int` by a `double` makes the build successful.

I suggest either the interface to be edited, or `ANPP` to be put as a double.

**Comment by rmscheller** [comment]
Clement,
It should be working now.  There was an update to universal cohort library.

**Comment by Klemet** [comment]
Thank you Robert ! Has this update been pushed already in the [Support libraries v8 repo](https://github.com/LANDIS-II-Foundation/Support-Library-Dlls-v8) ? I see commit 376dea1c53549057775bee83e99d8be4d7932cdc that affected the climate library, but it was from 5 days ago and should already be taken into account in what I'm doing.

**Comment by rmscheller** [comment]
Yes, the new cohort library has been pushed.

**Comment by Klemet** [comment]
I see; thank you !

But if this is indeed the push from 5 days ago, then it's the one that is giving me this error since it's the one I'm currently using.

**Comment by rmscheller** [comment]
Clement, I recompiled and tested yesterday with the latest version of the UCL.  I have no familiarity with Linux and so I can't begin to speculate why it isn't working on that platform.  Did you try to download and run on Windows?

**Comment by Klemet** [comment]
Aaaah, my mistake ! I'm sorry Robert, I think I misunderstood you. I see now that there was a new commit in this repository which fixes the issue; I thought you were talking about the 5 days-old update to the universal cohort library in the Support Library v8 repository.

I just checked, and everything works now with taking this latest commit into account. I apologize for the confusion.

Case closed !
